/*
Static OpenAPI document of Push API resource

Push API resources Open API documentation

API version: 0.3.15-sdk.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package databox

import (
	"encoding/json"
)

// checks if the PushDataAttribute type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PushDataAttribute{}

// PushDataAttribute struct for PushDataAttribute
type PushDataAttribute struct {
	Key *string `json:"key,omitempty"`
	Value *string `json:"value,omitempty"`
}

// NewPushDataAttribute instantiates a new PushDataAttribute object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPushDataAttribute() *PushDataAttribute {
	this := PushDataAttribute{}
	return &this
}

// NewPushDataAttributeWithDefaults instantiates a new PushDataAttribute object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPushDataAttributeWithDefaults() *PushDataAttribute {
	this := PushDataAttribute{}
	return &this
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *PushDataAttribute) GetKey() string {
	if o == nil || IsNil(o.Key) {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PushDataAttribute) GetKeyOk() (*string, bool) {
	if o == nil || IsNil(o.Key) {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *PushDataAttribute) HasKey() bool {
	if o != nil && !IsNil(o.Key) {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *PushDataAttribute) SetKey(v string) {
	o.Key = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *PushDataAttribute) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PushDataAttribute) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *PushDataAttribute) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *PushDataAttribute) SetValue(v string) {
	o.Value = &v
}

func (o PushDataAttribute) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PushDataAttribute) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Key) {
		toSerialize["key"] = o.Key
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

type NullablePushDataAttribute struct {
	value *PushDataAttribute
	isSet bool
}

func (v NullablePushDataAttribute) Get() *PushDataAttribute {
	return v.value
}

func (v *NullablePushDataAttribute) Set(val *PushDataAttribute) {
	v.value = val
	v.isSet = true
}

func (v NullablePushDataAttribute) IsSet() bool {
	return v.isSet
}

func (v *NullablePushDataAttribute) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePushDataAttribute(val *PushDataAttribute) *NullablePushDataAttribute {
	return &NullablePushDataAttribute{value: val, isSet: true}
}

func (v NullablePushDataAttribute) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePushDataAttribute) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


